packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@google/genai': true
  '@prisma/engines': true
  electron-winstaller: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  protobufjs: false
onlyBuiltDependencies:
  - esbuild
  - prisma
  - '@prisma/engines'
  - electron
  - electron-winstaller
  - msgpackr-extract
