packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  electron-winstaller: set this to true or false
  msgpackr-extract: set this to true or false
  prisma: set this to true or false
onlyBuiltDependencies:
  - esbuild
  - prisma
  - '@prisma/engines'
  - electron
  - electron-winstaller
  - msgpackr-extract
